/**
 * The methodology page.
 *
 * The state list and the evidence-kind list are derived from `src/types.ts`
 * rather than retyped, so the page cannot drift away from the enum the detector
 * actually switches on.
 */

import { readFileSync } from 'node:fs';

import { STATE_SEVERITY } from '../../src/types.js';
import type { EvidenceKind, MaintenanceState } from '../../src/types.js';

import { esc, joinLines, truncate } from './html.js';
import { href, type SiteContext } from './layout.js';
import type { RenderedPage } from './package.js';
import type { PageRecord } from './record.js';
import { indexSummary } from './record.js';

const DESCRIPTION =
  'How dead-deps decides that an npm package is unmaintained: the signals it reads, the evidence behind every verdict, why a quiet package is not a dead one, and the stable-complete guard that keeps finished packages out of the report.';

/** Where `npm run calibrate` leaves its machine-readable results. */
const CALIBRATION_RESULTS = new URL('../../docs/calibration-results.json', import.meta.url);

interface CalibrationBucket {
  rate: number;
  hits: number;
  support: number;
}

interface CalibrationResults {
  generatedAt: string;
  corpus: { rows: number };
  accuracy: { strict: { rate: number; correct: number; total: number }; lenient: { rate: number; correct: number; total: number } };
  headlineFalsePositiveRate: CalibrationBucket;
  falseAlarms: CalibrationBucket;
  missedDead: CalibrationBucket;
}

const percent = (value: number): string => `${(value * 100).toFixed(1)}%`;

/**
 * Renders the published accuracy numbers straight from the harness output.
 *
 * Deliberately never hand-written: a calibration figure that drifts from the
 * run that produced it is worse than no figure, so the page simply omits the
 * table when `npm run calibrate` has not been run.
 */
function calibrationTable(): string {
  let data: CalibrationResults;
  try {
    data = JSON.parse(readFileSync(CALIBRATION_RESULTS, 'utf8')) as CalibrationResults;
  } catch {
    return '<p class="note">Calibration numbers are generated by <code>npm run calibrate</code> and were not available when this page was built.</p>';
  }

  const rows: Array<[string, string, string]> = [
    [
      '<strong>False positives on finished packages</strong>',
      `<strong>${percent(data.headlineFalsePositiveRate.rate)}</strong>`,
      `${data.headlineFalsePositiveRate.hits} / ${data.headlineFalsePositiveRate.support} <code>stable-complete</code>`,
    ],
    [
      'False alarms on anything healthy',
      percent(data.falseAlarms.rate),
      `${data.falseAlarms.hits} / ${data.falseAlarms.support} healthy packages`,
    ],
    [
      'Missed dead packages',
      percent(data.missedDead.rate),
      `${data.missedDead.hits} / ${data.missedDead.support} genuinely dead`,
    ],
    [
      'Strict accuracy (exact state)',
      percent(data.accuracy.strict.rate),
      `${data.accuracy.strict.correct} / ${data.accuracy.strict.total}`,
    ],
    [
      'Lenient accuracy (near misses forgiven)',
      percent(data.accuracy.lenient.rate),
      `${data.accuracy.lenient.correct} / ${data.accuracy.lenient.total}`,
    ],
  ];

  return joinLines([
    '<div class="scroll-x">',
    '<table class="calibration">',
    '<thead><tr><th scope="col">Metric</th><th scope="col">Value</th><th scope="col">Basis</th></tr></thead>',
    '<tbody>',
    ...rows.map(([metric, value, basis]) => `<tr><td>${metric}</td><td>${value}</td><td>${basis}</td></tr>`),
    '</tbody>',
    '</table>',
    '</div>',
    `<p class="note">Corpus: ${esc(String(data.corpus.rows))} hand-labelled packages, measured on ${esc(data.generatedAt.slice(0, 10))}. The detector is scored on upstream signals alone here — the curated succession dataset is deliberately withheld from it, so these numbers are not inflated by answers it was handed.</p>`,
  ]);
}

const STATE_NOTES: Record<MaintenanceState, string> = {
  active: 'Releases, commits or issue responses within the recent window. Nothing to do.',
  'stable-complete':
    'Quiet, but finished rather than abandoned: small surface, no open bug pressure, still depended on heavily and still working. Never reported as a problem.',
  unknown:
    'Not enough coverage to judge — an unindexed package, a private registry, or a source that failed. Reported as ignorance, not as a verdict.',
  'low-activity':
    'Slower than its own history would predict, with some sign of life. Worth watching, not worth a migration.',
  unmaintained:
    'The release cadence has stopped relative to its own baseline, issues go unanswered, and no maintainer is visibly active.',
  deprecated:
    'The registry or the maintainers say so explicitly. This is a statement of fact from upstream, not an inference.',
  abandoned:
    'Unmaintained, plus a hard signal: an archived repository, a missing repository, or a maintainer statement that the project is over.',
  'hijack-risk':
    'Abandoned while still widely depended on, with a small bus factor or an unclaimed publish surface. The supply-chain case, ranked worst on purpose.',
};

const EVIDENCE_NOTES: Array<[EvidenceKind, string]> = [
  ['registry-deprecation', 'An explicit deprecation notice on the npm registry.'],
  ['repo-archived', 'The source repository is archived and read-only.'],
  ['repo-missing', 'The repository the package points at no longer resolves.'],
  ['release-cadence', 'The gap since the last release, measured against the package’s own median gap, not a fixed threshold.'],
  ['commit-activity', 'When the repository was last pushed to.'],
  ['issue-responsiveness', 'Issues and pull requests opened, closed and merged over the trailing year.'],
  ['bus-factor', 'How concentrated authorship is; a development distribution score near zero means one person.'],
  ['maintainer-activity', 'Whether upstream still considers any maintainer active.'],
  ['security-advisory', 'Open advisories against the package.'],
  ['dependent-flight', 'Dependents moving away faster than they arrive.'],
  ['curated-dataset', 'A hand-verified row in the succession dataset.'],
  ['stability-heuristic', 'Signals that argue the package is finished rather than abandoned. These carry negative weight.'],
];

export function renderMethodologyPage(site: SiteContext, pages: readonly PageRecord[]): RenderedPage {
  const states = (Object.keys(STATE_SEVERITY) as MaintenanceState[]).sort(
    (a, b) => STATE_SEVERITY[a] - STATE_SEVERITY[b],
  );

  const stateRows = states
    .map(
      (state) =>
        `<tr><td><code>${esc(state)}</code></td><td>${esc(String(STATE_SEVERITY[state]))}</td><td>${esc(
          STATE_NOTES[state],
        )}</td></tr>`,
    )
    .join('\n');

  const evidenceRows = EVIDENCE_NOTES.map(
    ([kind, note]) => `<tr><td><code>${esc(kind)}</code></td><td>${esc(note)}</td></tr>`,
  ).join('\n');

  const body = joinLines([
    `<nav class="small muted" aria-label="Breadcrumb"><a href="${esc(href(site, ''))}">dead-deps</a> / Methodology</nav>`,
    '<h1>How dead-deps decides a package is unmaintained</h1>',
    `<p class="lede">Every verdict is a state with sources attached, not a score with a threshold. This page describes what gets read, how it is weighed, what the tool refuses to claim, and the guard that keeps finished packages out of the report.</p>`,

    '<h2 id="signals">What gets read</h2>',
    '<p>Nothing is scraped and nothing is guessed. For each dependency the tool asks public indexes for a fixed set of facts: the registry’s own status and any deprecation message, the repository URL and whether it is archived, first and latest release dates, total version count, the median gap between releases across the package’s life, dependent counts, downloads, the development distribution score, committer count, issue and pull-request activity over the trailing year, the list of maintainers upstream still considers active, and any open advisories.</p>',
    '<p>Responses are cached on disk for a day by default, so a repeated scan costs nothing upstream. Sources that fail are recorded as failures rather than treated as zeroes — a network error must never read as "no activity".</p>',

    '<h2 id="evidence">Every claim carries its source</h2>',
    '<p>Each signal that argues for or against a verdict becomes a piece of evidence: a one-line human-readable label, a URL where you can check it, when the datum was observed upstream, and a signed weight. Negative weights argue that the package is alive. An unsourced verdict is treated as a bug in the tool, not as a judgement call.</p>',
    `<div class="scroll">
<table>
<caption class="small muted">Kinds of evidence a verdict can rest on.</caption>
<thead><tr><th scope="col">Kind</th><th scope="col">What it means</th></tr></thead>
<tbody>
${evidenceRows}
</tbody>
</table>
</div>`,

    '<h2 id="states">The verdict is a state, never a boolean</h2>',
    '<p>"Is this package dead" is the wrong question, because the interesting cases are the ones where the honest answer is "it is finished", "it is slowing down", or "we do not know". The tool sorts findings and sets its exit code by severity, so a CI gate can be pointed at exactly the states you care about with <code>--min-state</code>.</p>',
    `<div class="scroll">
<table>
<caption class="small muted">Maintenance states, mildest first. Severity is the sort key and the <code>--min-state</code> ordering.</caption>
<thead><tr><th scope="col">State</th><th scope="col">Severity</th><th scope="col">Meaning</th></tr></thead>
<tbody>
${stateRows}
</tbody>
</table>
</div>`,

    '<h2 id="quiet">Why "quiet" is not "dead"</h2>',
    '<p>The naive detector reads the date of the last release and calls anything old dead. It scores well on obviously dead projects and is still worthless, because a large share of the npm graph is tiny packages that were <em>finished</em> years ago. <code>once</code>, <code>wrappy</code>, <code>inherits</code>, <code>util-deprecate</code>, <code>imurmurhash</code>: they do one small thing, they do it correctly, there is nothing left to add, and so nobody commits to them. They are downloaded hundreds of millions of times a week.</p>',
    '<p>On last-release date alone those packages are indistinguishable from abandonware. Flagging them is not a harmless false positive — it is the failure mode that makes a maintenance tool useless, because a report full of things you must not act on trains you to ignore the report. Recommending that someone migrate off <code>inherits</code> has not found a problem; it has become one.</p>',

    '<h2 id="guard">The stable-complete guard</h2>',
    '<p>So "finished" is a first-class verdict with its own guard, and the guard runs before anything is reported. A package is treated as <code>stable-complete</code> rather than unmaintained when the picture is coherent: a long release history that settled down rather than stopped mid-flight; a small, stable API surface; no deprecation notice and no archived repository; no open advisories; no pile-up of unanswered issues relative to the package’s size; and continued heavy use by dependents that have had every opportunity to leave and have not.</p>',
    '<p>The guard is deliberately asymmetric. Any hard signal — a registry deprecation, an archived repository, an open advisory, a maintainer saying the project is over — overrides it immediately, because those are statements of fact rather than inferences from silence. Silence alone can only ever produce <code>stable-complete</code> or <code>low-activity</code>; it can never on its own produce <code>abandoned</code>.</p>',

    '<h2 id="confidence">Confidence, and admitting ignorance</h2>',
    '<p>Upstream indexes lag. A verdict built on two-year-old issue data has to say so rather than presenting it as current, so every assessment carries a confidence of high, medium or low derived from how much of the signal set was actually available and how fresh it was. When coverage is too thin to judge, the state is <code>unknown</code> and the package is not reported as a problem. "We could not find out" and "it is fine" are different answers and the tool keeps them apart.</p>',

    '<h2 id="succession">Where successors come from</h2>',
    `<p>What replaced a package cannot be inferred from metadata, so it is not. The successor half of every report comes from a hand-curated dataset in which each row is checked by a human against primary sources: an npm deprecation notice, a maintainer statement, an archived repository, a README, a release note, or an official migration guide. Blog posts are supporting evidence, never the only evidence.</p>`,
    '<p>A row is only added when the succession is consensus rather than opinion. Where reasonable engineers still disagree, the row is marked low confidence and the candidates are listed as alternatives instead of one being crowned. Rows about small, finished, still-working packages are refused outright — the dataset is a map of successions, not a list of packages someone finds unfashionable.</p>',
    `<p>Each row also records <em>how</em> the succession happened, because "a maintained fork exists" and "the platform absorbed it" call for completely different work. ${
      pages.length > 0
        ? `All ${esc(String(pages.length))} rows are published as <a href="${esc(href(site, '#index'))}">individual pages</a> with their evidence.`
        : 'Rows are published as individual pages with their evidence.'
    }</p>`,

    '<h2 id="calibration">Calibration</h2>',
    '<p>Because the false-positive claim above is the whole value of the tool, it is measured rather than asserted. A hand-labelled corpus of real packages — deliberately adversarial, and weighted toward finished-but-quiet ones — is scored against the detector, and the false-positive rate over the <code>stable-complete</code> bucket is reported separately from overall accuracy. A detector that flags finished packages fails calibration no matter how well it does elsewhere.</p>',
    calibrationTable(),

    '<h2 id="limits">What this cannot tell you</h2>',
    `<ul>
<li><strong>Whether you should migrate.</strong> An unmaintained dependency that is vendored, pinned and working may be a perfectly rational thing to keep. The tool reports state; the decision is yours.</li>
<li><strong>Anything about your own code.</strong> Only lockfile entries and public metadata are read. Nothing is uploaded.</li>
<li><strong>Private packages.</strong> Anything the public indexes do not carry comes back <code>unknown</code>.</li>
<li><strong>Whether a successor is good.</strong> The dataset records where the ecosystem went, which is not always where the best-engineered option was.</li>
</ul>`,

    relatedReading(site, pages),
  ]);

  return {
    meta: {
      title: 'Methodology — how dead-deps decides an npm package is unmaintained',
      description: DESCRIPTION,
      path: 'methodology/',
      ogType: 'article',
      structuredData: [techArticle(site)],
    },
    body,
  };
}

function relatedReading(site: SiteContext, pages: readonly PageRecord[]): string {
  if (pages.length === 0) {
    return `<h2 id="next">Next</h2>\n<p><a href="${esc(href(site, ''))}">Back to the package index</a>.</p>`;
  }
  const sample = pickSpread(pages, 4);
  const items = sample
    .map(
      (page) =>
        `<li><a href="${esc(href(site, page.path))}"><span class="name">${esc(
          page.record.from,
        )}</span><span class="says">${esc(truncate(indexSummary(page.record), 90))}</span></a></li>`,
    )
    .join('\n');
  return joinLines([
    '<h2 id="next">See it applied</h2>',
    `<ul class="cards">\n${items}\n</ul>`,
    `<p><a href="${esc(href(site, ''))}">Back to the full package index</a>.</p>`,
  ]);
}

/** Evenly spaced picks, so the sample is not four packages starting with "a". */
function pickSpread(pages: readonly PageRecord[], count: number): PageRecord[] {
  if (pages.length <= count) return [...pages];
  const step = pages.length / count;
  const picked: PageRecord[] = [];
  for (let i = 0; i < count; i += 1) {
    const page = pages[Math.floor(i * step)];
    if (page !== undefined) picked.push(page);
  }
  return picked;
}

function techArticle(site: SiteContext): unknown {
  const url = `${site.baseUrl}methodology/`;
  return {
    '@context': 'https://schema.org',
    '@type': 'TechArticle',
    '@id': `${url}#article`,
    headline: 'How dead-deps decides an npm package is unmaintained',
    name: 'Methodology',
    description: DESCRIPTION,
    url,
    inLanguage: 'en',
    dateModified: site.buildDate,
    articleSection: 'Methodology',
    proficiencyLevel: 'Expert',
    dependencies: 'Node.js 20 or newer',
    isPartOf: { '@type': 'WebSite', name: site.name, url: site.baseUrl },
    about: [
      { '@type': 'Thing', name: 'npm dependency maintenance' },
      { '@type': 'Thing', name: 'software supply chain' },
    ],
    mainEntityOfPage: url,
  };
}
